cloud:
  aws:
    credentials:
      accessKey: ${access}
      secretKey: ${saccess}
    s3:
      bucket: bucket-ali2
    region:
      static: ap-northeast-2
    stack:
      auto: false

spring:
  datasource:
    url: ${DB_URL}
    username: admin
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: inhees98@gmail.com
    password: xxac auuo gvqe kouf
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
  thymeleaf:
    cache: false
  cache:
    redis:
      port: '6379'
      host: ${REDIS_HOST}
    type: redis

jwt:
  secret:
    key: 7JWI64WV7ZWY7IS47JqUIO2Vre2VtDE26riwIDE17KGw7J6F64uI64ukLg
